Enable on-chain head identifiers
  Add failing ETE test with 2 competing Heads

  remove 'PostTxFailed' branch on 'OnChainTx'

    Now dead code.

  Make tests pass by ignoring "irrelevant" transactions at the cost of a traceShow

  Drop 'IgnoredTx' as we would be able to infer it from 'ReceivedTxs'

  Add note about concurrent end-to-end test

  Change keysFor and writeKeysFor to take an Actor = Alice | Bob | Carol

  Add 'faucet' keys and Actor

  Draft a seedFromFaucet function

  Add Faucet to initial funds distribution in EndToEnd

  Implement seedFromFaucet

    This is now an alternative to initialFunds + postSeedPayment

  Make seedFromFaucet mark outputs when requested

  Slightly improve error/assertion reporting

  Update & fix amounts payed / transferred in EndToEnd test

  Return 'Utxo' from some CardanoClient functions

  Factor out initAndClose in EndToEnd

  Use waitForPayment in seedFromFaucet again

  Add another EndToEnd test which concurrently opens two Heads on the same network

  Only wrap 'connectTo' exception in the direct-chain

    We happened to include the 'action' in the handler, which happened to catch _any IOException_ thrown by child components. This leads to very misleading error reporting.

  Wrap server listen exception in more context.

  Wrap API's 'runServer' exceptions into exceptions with more context.

  Use withHydraCluster to be able to have different nodeIds for each cluster

  Fix an off-by-one error

  Add a firstNodeId to withHydraCluster

  Remove cruft around 'waitForNodeConnected'

    We can figure out the node id from the 'HydraClient' already.

  Offset first node id in end-to-end 'initAndClose' scenario.

    That's how we get to bind nodes on different ports.

  Retry tx submission in tests

    We retry indefinitely on the CardanoClientException, relying on timeout at the tests level.

  Fix compilation errors following rebase

    This implies the previous commits do not compile, perhaps I should have fixed each of them, or perhaps we don't care.

  Draft logic to ignore/process chain observations

    This makes a case that we would need to have two functions, currently named getHeadId and getOBservedHeadId

  Initialise headId with default value

  Find the first minted state token in observeInitTx

  [wip] Introduce minting policy script for head tokens

  Filled in the gaps of minting state thread tokens

  [wip] Draft mintTokens signature

  Implement 'mintTokens'.

  Fixup: 16ebe423, add 'ScriptWitness' constructor in tx-cost.

  Change observeInitTx to look for ST in head output

  Put the ST into the headOutput in initTx

  [wip] Pass policy Id around for making head output

  Define 'headPolicyId' to create a Head PolicyId from a TxIn (a.k.a TxOutRef)

  Use testPolicy in test Direct.Contract code

  Add UsingRawBytesHex and introduce a HeadId in Hydra.Chain

  Add 'HeadId' to the OnChainTx's InitTx branch.

    Later, we want to have it for ALL on-chain txs, but we start with baby steps.

  Add InitTx's 'headId' to JSON-schema for the logs API.

  re-generate golden samples for Hydra' events.

  Improve error message on failing collectComTx spec

    Now we get:

    ```
    Script Evaluation(s):
      - RdmrPtr Spend 0: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1779374, exUnitsSteps' = 737070427}}
      - RdmrPtr Spend 1: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1779374, exUnitsSteps' = 737070427}}
      - RdmrPtr Spend 2: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1779374, exUnitsSteps' = 737070427}}
      - RdmrPtr Spend 3: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1782698, exUnitsSteps' = 739043390}}
      - RdmrPtr Spend 4: ValidationFailedV1 (CekError An error has occurred:  User error: The provided Plutus code called 'error'.) ["wrong output head value","PT5"]
      - RdmrPtr Spend 5: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1779374, exUnitsSteps' = 737070427}}
      - RdmrPtr Spend 6: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1782698, exUnitsSteps' = 739043390}}
      - RdmrPtr Spend 7: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1779374, exUnitsSteps' = 737070427}}
      - RdmrPtr Spend 8: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1782698, exUnitsSteps' = 739043390}}
      - RdmrPtr Spend 9: WrapExUnits {unWrapExUnits = ExUnits' {exUnitsMem' = 1779374, exUnitsSteps' = 737070427}}
    ```

    which makes it quite obvious that the head value is wrong and caught by the head contract! Indeed, we still use a hard-coded head value in the collect-com construction instead of forwarding the head value (and the ST).